techpack: display: dsi: implement gamma support
since fog can overclock refresh rate > 60 I want to implement gamma support for fog from
https://gitlab.com/sourceslab062/sdm680/-/commit/81eb8b70772426af5844de9bf7b68f761b260794

--
Squashed:
	techpack: display: dsi: since fog can overclock refresh rate > 60, i want to implement gamma support for fog from
	fix error ../techpack/display/msm/sde/sde_encoder.c:5070:21: error: no member named 'dsi_refresh_flag' in 'struct dsi_panel'
	fix errror ../techpack/display/msm/dsi/dsi_panel.c:536:2: error: use of undeclared identifier 'refresh_rate'

taken from Kribo's kernel